# 'project' is the highest level instruction for Quarto
# It informs the handling of the entire repository
project:
  # 'website' tells it to render .md files as interconnected
  # HTML webpages
  type: website

# instructions in 'website' control global website features
website:
  title: "Saxon Stockton<br><small style='font-weight: normal; color: #6c757d;'>Astrophysics PhD Student<br>Texas Christian University<\small>"
  # 'description' contains metadata for the website
  description: "Astrophysics Research and Teaching Portfolio"
  # 'sidebar' gives a left-handed navigation menu
  sidebar:
    # 'docked' pins the sidebar to the screen
    # 'floating' makes sidebar toggleable
    style: floating
    # 'search' adds a built-in search bar that looks inside
    # the .md files
    search: true
    # 'contents' informs the sidebar links
    tools:
      - icon: envelope
        href: mailto:s.stockton@tcu.edu
      - icon: github
        href: https://github.com/purplinator
        
    contents:
      - text: "Home"
        icon: house-door
        file: index.md
      - section: "Research"
        contents:
          - text: "Large Megallanic Cloud"
            file: lvm_research.qmd
          - text: "Code Docs"
            file: lvm_code_docs.qmd
      - text: "Research Placeholder"
        file: research.md
      - text: "Teaching"
        file: teaching.md

# 'format' controls the final output
format:
  html:
    css: styles.css # Connecting to information on styling the sidebar
    theme: cosmo # A clean, professional academic theme
    toc: true    # Automatically adds a table of contents to long pages
