project:
  type: website

website:
  title: "Saxon Stockton"
  description: "Astrophysics Research and Teaching Portfolio"
  sidebar:
    style: docked
    search: true
    contents:
      - text: "Home"
        file: index.md
      - text: "Research"
        file: research.md
      - text: "Teaching"
        file: teaching.md

format:
  html:
    theme: cosmo # A clean, professional academic theme
    toc: true    # Automatically adds a table of contents to long pages
